### ISSUE TITLE
There's a bug!

### ISSUE THREAD

**Issue by LPGhatguy** [Eurydamas/CSharp-Git-Tests#1]
Everything's on fire!

**Comment by Eurydamas** [comment]
I think I dumped enough water on it to fix it all.

**Comment by LPGhatguy** [comment]
Our servers have stopped burning and are mostly just smoldering.

**Comment by Eurydamas** [comment]
Good. Keep them partially submerged for best results. Might wanna splash the processors a few times just to make sure they stay cool enough.
